provider: aws

policy: upsert-only

registry: txt
txtOwnerId: keto-project

domainFilters:
  - shamimchaudhury.uk

serviceAccount:
  create: true
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: 

# annotations are like sticky notes
# telling external-dns to use aws eks role arn for the service account 