apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.0
    helm:
      values: |
        installCRDs: true

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
    
  syncPolicy:
     syncOptions:
       - CreateNamespace=true
     automated:
      prune: true
      selfHeal: true
