apiVersion: apps/v1
kind: Deployment
metadata:
  name: keto-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: keto-app
  template:
    metadata:
      labels:
        app: keto-app
    spec:
      containers:
        - name: keto-app
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
