apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "keto-app.fullname" . }}
spec:
  ingressClassName: {{ .Values.className }}
  rules:
    - host: {{ .Values.ingress.paths.path }}
      pathType: Prefix
      backend:
       service:
         name: keto-service
         port: 
           number: {{ .Values.service.port }}


