apiVersion: v1
kind: Service
metadata:
  name: keto-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "keto-app.selectorLabels" . | nindent 4 }}
