replicaCount: 2

image:
  repository: 317006682416.dkr.ecr.eu-west-2.amazonaws.com/keto-app
  pullPolicy: IfNotPresent
  tag: "latest" ### Will change later

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: traefik 
  hosts:
    - eks.shamimchaudhury.uk
  paths:
    - /
      
